/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tt.kafka.example.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InnerData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1143440405669562278L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InnerData\",\"namespace\":\"com.tt.kafka.example.avro\",\"fields\":[{\"name\":\"dataId\",\"type\":\"int\"},{\"name\":\"dataCommit\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InnerData> ENCODER =
      new BinaryMessageEncoder<InnerData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InnerData> DECODER =
      new BinaryMessageDecoder<InnerData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<InnerData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<InnerData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InnerData>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this InnerData to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a InnerData from a ByteBuffer. */
  public static InnerData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int dataId;
  @Deprecated public java.lang.CharSequence dataCommit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InnerData() {}

  /**
   * All-args constructor.
   * @param dataId The new value for dataId
   * @param dataCommit The new value for dataCommit
   */
  public InnerData(java.lang.Integer dataId, java.lang.CharSequence dataCommit) {
    this.dataId = dataId;
    this.dataCommit = dataCommit;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return dataId;
    case 1: return dataCommit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: dataId = (java.lang.Integer)value$; break;
    case 1: dataCommit = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'dataId' field.
   * @return The value of the 'dataId' field.
   */
  public java.lang.Integer getDataId() {
    return dataId;
  }

  /**
   * Sets the value of the 'dataId' field.
   * @param value the value to set.
   */
  public void setDataId(java.lang.Integer value) {
    this.dataId = value;
  }

  /**
   * Gets the value of the 'dataCommit' field.
   * @return The value of the 'dataCommit' field.
   */
  public java.lang.CharSequence getDataCommit() {
    return dataCommit;
  }

  /**
   * Sets the value of the 'dataCommit' field.
   * @param value the value to set.
   */
  public void setDataCommit(java.lang.CharSequence value) {
    this.dataCommit = value;
  }

  /**
   * Creates a new InnerData RecordBuilder.
   * @return A new InnerData RecordBuilder
   */
  public static com.tt.kafka.example.avro.InnerData.Builder newBuilder() {
    return new com.tt.kafka.example.avro.InnerData.Builder();
  }

  /**
   * Creates a new InnerData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InnerData RecordBuilder
   */
  public static com.tt.kafka.example.avro.InnerData.Builder newBuilder(com.tt.kafka.example.avro.InnerData.Builder other) {
    return new com.tt.kafka.example.avro.InnerData.Builder(other);
  }

  /**
   * Creates a new InnerData RecordBuilder by copying an existing InnerData instance.
   * @param other The existing instance to copy.
   * @return A new InnerData RecordBuilder
   */
  public static com.tt.kafka.example.avro.InnerData.Builder newBuilder(com.tt.kafka.example.avro.InnerData other) {
    return new com.tt.kafka.example.avro.InnerData.Builder(other);
  }

  /**
   * RecordBuilder for InnerData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InnerData>
    implements org.apache.avro.data.RecordBuilder<InnerData> {

    private int dataId;
    private java.lang.CharSequence dataCommit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tt.kafka.example.avro.InnerData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.dataId)) {
        this.dataId = data().deepCopy(fields()[0].schema(), other.dataId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dataCommit)) {
        this.dataCommit = data().deepCopy(fields()[1].schema(), other.dataCommit);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InnerData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tt.kafka.example.avro.InnerData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.dataId)) {
        this.dataId = data().deepCopy(fields()[0].schema(), other.dataId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dataCommit)) {
        this.dataCommit = data().deepCopy(fields()[1].schema(), other.dataCommit);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'dataId' field.
      * @return The value.
      */
    public java.lang.Integer getDataId() {
      return dataId;
    }

    /**
      * Sets the value of the 'dataId' field.
      * @param value The value of 'dataId'.
      * @return This builder.
      */
    public com.tt.kafka.example.avro.InnerData.Builder setDataId(int value) {
      validate(fields()[0], value);
      this.dataId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'dataId' field has been set.
      * @return True if the 'dataId' field has been set, false otherwise.
      */
    public boolean hasDataId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'dataId' field.
      * @return This builder.
      */
    public com.tt.kafka.example.avro.InnerData.Builder clearDataId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataCommit' field.
      * @return The value.
      */
    public java.lang.CharSequence getDataCommit() {
      return dataCommit;
    }

    /**
      * Sets the value of the 'dataCommit' field.
      * @param value The value of 'dataCommit'.
      * @return This builder.
      */
    public com.tt.kafka.example.avro.InnerData.Builder setDataCommit(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.dataCommit = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'dataCommit' field has been set.
      * @return True if the 'dataCommit' field has been set, false otherwise.
      */
    public boolean hasDataCommit() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'dataCommit' field.
      * @return This builder.
      */
    public com.tt.kafka.example.avro.InnerData.Builder clearDataCommit() {
      dataCommit = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InnerData build() {
      try {
        InnerData record = new InnerData();
        record.dataId = fieldSetFlags()[0] ? this.dataId : (java.lang.Integer) defaultValue(fields()[0]);
        record.dataCommit = fieldSetFlags()[1] ? this.dataCommit : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InnerData>
    WRITER$ = (org.apache.avro.io.DatumWriter<InnerData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InnerData>
    READER$ = (org.apache.avro.io.DatumReader<InnerData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
